export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  RATE_LIMITED: 'RATE_LIMITED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_REUSE_DETECTED: 'REFRESH_REUSE_DETECTED',
  EMAIL_TAKEN_BIND_REQUIRED: 'EMAIL_TAKEN_BIND_REQUIRED',
  GITHUB_ALREADY_BOUND: 'GITHUB_ALREADY_BOUND',
  CANNOT_UNBIND_LAST_METHOD: 'CANNOT_UNBIND_LAST_METHOD',
  INVALID_UPLOAD: 'INVALID_UPLOAD',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CANNOT_FOLLOW_SELF: 'CANNOT_FOLLOW_SELF',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  SLUG_TAKEN: 'SLUG_TAKEN',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
